name: Build Nextcloud Multi-Arch

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  # We'll normalize to lowercase + set the final full name later
  IMAGE_NAME: ${{ github.repository_owner }}/nextcloud-docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/nekosunevr/nextcloud-docker:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
